// SLURM Arguments for platform execution
// These are stored as arguments but linked to a special "SLURM" program for platform execution

const slurmArgumentsData = [
  // Resource allocation
  {
    name: '--nodes',
    value_type: 'NUMBER',
    allowed_values: [],
    is_required: false,
    default_value: '1',
    is_flag: false,
    description: 'Number of nodes to allocate',
    min_value: 1,
    max_value: 1000,
    min_length: null,
    max_length: null,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to SLURM program
  },
  {
    name: '--ntasks',
    value_type: 'NUMBER',
    allowed_values: [],
    is_required: false,
    default_value: '1',
    is_flag: false,
    description: 'Total number of tasks',
    min_value: 1,
    max_value: 10000,
    min_length: null,
    max_length: null,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to SLURM program
  },
  {
    name: '--cpus-per-task',
    value_type: 'NUMBER',
    allowed_values: [],
    is_required: false,
    default_value: '1',
    is_flag: false,
    description: 'Number of CPUs per task',
    min_value: 1,
    max_value: 128,
    min_length: null,
    max_length: null,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to SLURM program
  },
  {
    name: '--mem',
    value_type: 'STRING',
    allowed_values: [],
    is_required: false,
    default_value: null,
    is_flag: false,
    description: 'Memory per node (e.g., 4G, 8GB)',
    min_value: null,
    max_value: null,
    min_length: 1,
    max_length: 20,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to SLURM program
  },
  {
    name: '--time',
    value_type: 'STRING',
    allowed_values: [],
    is_required: false,
    default_value: null,
    is_flag: false,
    description: 'Time limit (DD-HH:MM:SS format)',
    min_value: null,
    max_value: null,
    min_length: 8,
    max_length: 12,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to SLURM program
  },
  {
    name: '--job-name',
    value_type: 'STRING',
    allowed_values: [],
    is_required: false,
    default_value: null,
    is_flag: false,
    description: 'Name for the SLURM job',
    min_value: null,
    max_value: null,
    min_length: 1,
    max_length: 100,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to SLURM program
  },
  {
    name: '--partition',
    value_type: 'STRING',
    allowed_values: ['cpu', 'gpu', 'highmem', 'interactive', 'debug'],
    is_required: false,
    default_value: null,
    is_flag: false,
    description: 'SLURM partition to use',
    min_value: null,
    max_value: null,
    min_length: null,
    max_length: 50,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to SLURM program
  },
  {
    name: '--output',
    value_type: 'STRING',
    allowed_values: [],
    is_required: false,
    default_value: 'job_%j.out',
    is_flag: false,
    description: 'File for standard output',
    min_value: null,
    max_value: null,
    min_length: 1,
    max_length: 200,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to SLURM program
  },
  {
    name: '--error',
    value_type: 'STRING',
    allowed_values: [],
    is_required: false,
    default_value: 'job_%j.err',
    is_flag: false,
    description: 'File for standard error',
    min_value: null,
    max_value: null,
    min_length: 1,
    max_length: 200,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to SLURM program
  },
  {
    name: '--mail-type',
    value_type: 'STRING',
    allowed_values: ['NONE', 'BEGIN', 'END', 'FAIL', 'REQUEUE', 'ALL'],
    is_required: false,
    default_value: null,
    is_flag: false,
    description: 'When to send email notifications (comma-separated)',
    min_value: null,
    max_value: null,
    min_length: null,
    max_length: 50,
    position: null,
    dynamic_variable_name: null,
    program_id: null, // Will be set during seeding - links to SLURM program
  },
];

module.exports = {
  slurmArgumentsData,
};
