// https://pm2.keymetrics.io/docs/usage/application-declaration/
module.exports = {
  // replace script [python] with path of poetry's python executable
  apps: [
    {
      name: "celery_worker",
      script: "python",
      args: "-m celery -A workers.fetch_celery_app worker --loglevel INFO -O fair --pidfile celery_worker.pid --hostname 'cmg-celery-fetch-w1@%h' --autoscale=8,2 --queues 'fetch.cmg-test.sca.iu.edu.q'",
      watch: false,
      interpreter: "",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "../logs/workers/celery_worker.err",
      out_file: "../logs/workers/celery_worker.log",
      kill_timeout: "10000",
      exp_backoff_restart_delay: 100,
      max_restarts: 3,
    },
    {
      name: "conversions_worker",
      script: "python",
      args: "-m celery -A workers.conversions_app worker --loglevel INFO -O fair --pidfile conversions_worker.pid --hostname 'cmg-celery-conversions-w1@%h' --autoscale=8,2 --queues 'conversion.cmg-test.sca.iu.edu.q' --statedb=conversions_worker_state.db",
      watch: false,
      interpreter: "",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "../logs/workers/conversions_worker.err",
      out_file: "../logs/workers/conversions_worker.log",
      kill_timeout: "10000",
      exp_backoff_restart_delay: 100,
      max_restarts: 3,
    },
    {
      name: "metrics",
      script: "python",
      args: "-u -m workers.scripts.metrics",
      watch: false,
      interpreter: "",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "../logs/workers/metrics.err",
      out_file: "../logs/workers/metrics.log",
      cron_restart: "00 21 * * *",
      autorestart: false,
      exp_backoff_restart_delay: 100,
      max_restarts: 3,
    },
    {
      name: "purge_staged_datasets",
      script: "python",
      args: "-u -m workers.scripts.purge_staged_datasets",
      watch: false,
      interpreter: "",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "../logs/workers/purge_staged_datasets.err",
      out_file: "../logs/workers/purge_staged_datasets.log",
      cron_restart: "00 07 * * *",
      autorestart: false,
      exp_backoff_restart_delay: 100,
      max_restarts: 3,
    },
    {
      name: "purge_stale_workflows",
      script: "python",
      args: "-u -m workers.scripts.purge_stale_workflows",
      watch: false,
      interpreter: "",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "../logs/workers/purge_stale_workflows.err",
      out_file: "../logs/workers/purge_stale_workflows.log",
      cron_restart: "00 07 * * *",
      autorestart: false,
      exp_backoff_restart_delay: 100,
      max_restarts: 3,
    },
    {
      name: "manage_upload_workflows",
      script: "python",
      args: "-u -m workers.scripts.manage_upload_workflows --dry-run=False --max-retries=3",
      watch: false,
      interpreter: "",
      log_date_format: "YYYY-MM-DD HH:mm Z",
      error_file: "../logs/workers/manage_upload_workflows.err",
      out_file: "../logs/workers/manage_upload_workflows.log",
      cron_restart: "* * * * *",  // Run every 1 minute - processes stalled uploads and retries failures
      autorestart: false,
      exp_backoff_restart_delay: 100,
      max_restarts: 3,
    }
  ]
}
